import { initialDataAtom } from 'jotai-query-toolkit';
import { Atom } from 'jotai/core/atom';
import { hashQueryKey } from 'react-query';

/**
 * useQueryInitialValues
 *
 * This hook is made to be used on next.js pages only to provide the initial data for our query atoms.
 * Note: This should only be used by advanced users, withInitialQueries makes use of this internally.
 *
 * ```typescript
 * const queryKeys = [SomeEnum.SomeKey];
 * const props = { '["SomeEnum.SomeKey"]": { foo: "bar' } }; // this will be autogenerated via {@link getInitialPropsFromQueries}`
 * const initialValues = useQueryInitialValues(queryKeys, props);
 * ```
 *
 * @param props - the data generated from {@link getInitialPropsFromQueries}, should not be created manually.
 */
export function useQueryInitialValues(props?: Record<string, unknown>) {
  const queryKeys = props ? Object.keys(props) : [];
  const atoms = queryKeys.map(queryKey => {
    if (queryKey && props && !(queryKey in props))
      throw Error(`[Jotai Query Toolkit] no initial data found for ${hashQueryKey(queryKey)}`);
    const value = props ? props[queryKey] : null;
    return [initialDataAtom(queryKey), value] as const;
  });
  return [...atoms] as Iterable<readonly [Atom<unknown>, unknown]>;
}
